title:             Nessie's Keto Kitchen
email:             nessiesketokitchen@gmail.com
description:       Ketogenic lifestyle blog
author:            Ann√©s Keyter
baseurl:           "/"
url:               "https://nessiesketokitchen.github.io"

# Social Profiles
# twitter_username:  SBootstrap
# github_username:   BlackrockDigital
instagram_username: nessiesketokitchen
facebook_username: nessiesketokitchen

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
